# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.runs/synth_1/camera.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.cache/wt [current_project]
set_property parent.project_path C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/debouncer.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/histogram.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/i2c_sender.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/effects/negative.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/oled_display.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/ov7670_capture.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/ov7670_controller.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/ov7670_registers.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/effects/rgb_to_gray.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/effects/sad.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/effects/sobel.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/video.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/video_timing.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/effects/xor.vhd
  C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera.vhd
}
read_ip -quiet C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/ddr/ddr.xci
set_property used_in_implementation false [get_files -all c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc]
set_property used_in_implementation false [get_files -all c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc]

read_ip -quiet C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/line_buffer/line_buffer.xci
set_property used_in_implementation false [get_files -all c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/line_buffer/line_buffer_ooc.xdc]

read_ip -quiet C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/saredar/camera_using_external_memory_ece441_2026_02_V1_12/camera_using_external_memory/camera_using_external_memory.srcs/utils_1/imports/synth_1/camera.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top camera -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef camera.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file camera_utilization_synth.rpt -pb camera_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
